### ISSUE TITLE
Read-only data

### ISSUE THREAD

**Issue by npruehs** [npruehs/tome-editor#68]
We need to be able to mark records, fields, components and types to marked _read-only_:

* Read-only data can't be edited in Tome.
* Setting data read-only (or removing the read-only) flag can't be done in Tome, but only by editing the respective data file manually. Trying to do show will show a message box with an explanation instead.

**Comment by npruehs** [comment]
Added in commit 12fe412e70297ab8a0397b2ef9f374f08acab934.

@pgrimsehl Can you take a look at this and verify this works as intended for you? I've added records, only, yet. I'm thinking that it might be a cleaner solution to remove the "Fields" menu altogether for your released builds, effectively removing the possibility of editing any fields, components or types. That should fit your needs, right? Do we want this at application-level (e.g. #define) or at data-level (e.g. XML attribute in the project file)?

**Comment by pgrimsehl** [comment]
Flagging individual records as read-only is great, but since this information is stored in the .tdata file, the access modifier cannot be set on a per project basis, which was my intention. An owner/editor of a  "master" project should be able to modifiy all records.
I'd really like to see this access modifier as parameter for each record set in the project file, effectively locking all records of a set.

Additionally, flagging a parent as read-only will not flag it's children in the current implementation. Of course it is debatable if the current set of children is part of the record definition and must not be changed if the record read-only.

A minor issue is the lock icon, which completely replaces the record icon. If user defined icons for individual records (#21) are implemented, this will occlude the user icon. Maybe a small lock overlay icon in the upper left corner of the icon would be better (not sure if this can be done, but multiple decoration role items shpuld be possible)

**Comment by npruehs** [comment]
Okay, I'm still not sure what's your use case here. In my head, I was always imagining the following setup:

Master Project:
* contains root objects, such as "Ability" or "Building"
* edited by programmers, in most cases
* used for bookkeeping of fields, components, and the fields of the root object

Sub Project:
* edited by game designers (or even plaeyrs), in most cases
* create new children for the roots, effectively adding new abilities or buildings, for example
* must not be able to accidentally modify the roots, or any fields, which would break the game

If children of a read-only record would inherit that attribute, the above scenario wouldn't work any more. Maybe you can provide an example setup (base case: the project files, stripped down if you'd like), maybe per mail if you don't want to share it publically. That would help a lot outlining what you're trying to do.

Yeah, I didn't want to use the lock icon, but colorize the name of the record instead, but that's not (easily) possible in Qt. I'm open for other suggestions.

**Comment by pgrimsehl** [comment]
That's why I said its debatable ;) I think your example will be the most common, so it really would not make sense to lock children by default.

But still, locking the root objects by setting the ReadOnly attribute in the master .tdata file (which is shared by master and sub projects) will prevent these records from being altered in the master project.

**Comment by npruehs** [comment]
I see your point. I've added an XML attribute "IgnoreReadOnly" to the TomeProject element of project files in commit 8905ea3dad22f4909c845180b07e4e1285b651d9. Setting this attribute effectively makes the project file a "master" project in your definition, allowing you to change read-only records. The master project still shows the lock icon. Tell me if that's feasible for you.

**Comment by pgrimsehl** [comment]
Hi Nick! The `IgnoreReadOnly` attribute worke for me :)

**Comment by npruehs** [comment]
Glad to hear :)
