### ISSUE TITLE
Master / Child projects

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#70]
During distributed content development it will be very helpful to have some kind of "Master Project" which defines

- Custom Data Types
- Components
- Field Definitions
- Parent Records

These definitions are used in "Child Projects" which reference the "Master Project". A project is master project by default, so only child projects must have a special state. Ideally, in a child project you cannot

- add / remove / change field definitions
- add / remove / change components
- add / remove / change root records

This way content designers can work with a given project layout set by the root records and a set of definitions at their disposal to build new data structures without breaking anything.

Of course this opens up the need for new data integrity checks, as the child projects must be aware of changes in the master project when they are opened. This includes for example

- added / removed / changed fields
- added / removed / changed components 
- added / removed / changed records

There are many cases where changes in the master project cannot be applied to child projects in an automated process ( e.g. changing a field type from Int to Enum ), but there has to be a detailed data integrity report for the user, so these conflicts can be resolved manually.

Current state: additional field and record sets not located in the project folder can be referenced in a project, but this information in incomplete, since Custom Types, Type Maps and Components must be redefined / replicated in each project. This data is not read-only ( though this might change in future versions of Tome, see #68 ). There is no data integrity check.

**Comment by npruehs** [comment]
I could image moving Custom Types, Type Maps and Components to dedicated files, which should be pretty easy to do - would that help? I'm a little hesitant to introduce the concept of "child" projects as a fundamental concept, because we've had trouble with these for about a decade here (might be a personal thing by now ;) ) Moving this data to dedicated files would allow you to re-use them across arbitrary projects, which sounds like a powerful idea to me. I could even imagine loading them from the web or some read-only place in your local network, if that's a requirement.

As for the data integrity check: Yes, we need that. Right now, I think field values are reset to their defaults if their type is changed. While this behaviour is totally fine in some cases, it might not in others. Sounds like something we'd want to add to the #16 Project Settings.

**Comment by pgrimsehl** [comment]
Moving these defintions to dedicated files will suffice, as it has the same effect as the master / child combination.

**Comment by npruehs** [comment]
Great, will do!

**Comment by npruehs** [comment]
Added in commit d874e038a28fea5501785dbe0317e67a13f235e5.

**Comment by npruehs** [comment]
@pgrimsehl Just a pingback to notify you this has been added.
