### ISSUE TITLE
Export Records As Separate Files

### ISSUE THREAD

**Issue by ForgeMistress** [npruehs/tome-editor#92]
One of the other things that I had been wishing this tool had was the option to export a project with multiple records as separate files. Right now I'm working around this by using several projects and referencing several global type and component files, but one of the things that would be useful for things such as global data files would be the option to export one project with several records as multiple separate files.

(Also, brace yourself, I have quite a few feature ideas.)

**Comment by npruehs** [comment]
How do you suggest to decide which records to put into which exported file?

**Comment by WildPyromancer** [comment]
I'm thinking the best option would probably be a check box that can be flagged in the Edit Record dialog. It might also be useful to expose this to the exporter templates. I probably wouldn't use it, but it would probably be useful for someone else.

**Comment by WildPyromancer** [comment]
Export the value of the flag I mean.

**Comment by WildPyromancer** [comment]
And also provide a text box if it's flagged for the user to provide a file name and path.

**Comment by npruehs** [comment]
Hmm, I can't seem to  come up with a comprehensive UI for this. What if you've got ten export templates in your project? Show ten checkboxes and ten textboxes in the Edit Record dialog? Have the user add the same export path to each textbox of each record for each export template?

I am also hesitant to add a feature because it "would probably be useful". As soon as you've got a use case for this, I'm happy to discuss this :)

Until then, I'd recommend use multiple project files and export templates. Note that you can explicitly tell export templates to export roots, internal nodes and/or leaves, and also define records that should be ignored. See https://github.com/npruehs/tome-editor/wiki/Exporting-Data#adding-export-templates for details.
